baseURL: "https://blog.bensheppard.dev/"
title: "Inside my mind"
theme: hugo-theme-stack
params:
  description: "A space for me to write about things I'm interested in."
  keywords: [Blog, Warhammer, Creative, allotment, coding, software]
  author:
    name: "Ben Sheppard"
    email:
  mainSections:
    - post
  widgets:
    homepage:
      - type: categories
        params:
          limit: 10
    page:
      - type: toc
  imageProcessing:
    cover:
      enabled: true
    content:
      enabled: true
  menu:
    main: [ ]
  sidebar:
    subtitle: "I am a software engineer with interests that are not always related to my job, this is a blog about them."
  markup:
    tableOfContents:
      endLevel: 3
      ordered: true
      startLevel: 1
