baseURL: "https://blog.bensheppard.dev/"
title: "Ben's Blog"
theme: PaperMod
params:
  title: "Ben's Blog"
  description: "A space for me to write about things I'm interested in."
  keywords: [Blog, Warhammer, Creative, allotment, coding, software]
  author: Ben Sheppard
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
sectionPagesMenu: main